CREATE DATABASE EmployeeDB;
GO

CREATE DATABASE EmployeeDB;
GO

CREATE TABLE MY_EMPLOYEES (
    ID INT NOT NULL PRIMARY KEY,
    LAST_NAME VARCHAR(25),
    FIRST_NAME VARCHAR(25),
    USERID VARCHAR(8),
    SALARY DECIMAL(9,2)
);

INSERT INTO MY_EMPLOYEES
VALUES (1, 'Priya', 'Raj', 'rpriya', 895);

INSERT INTO MY_EMPLOYEES (ID, LAST_NAME, FIRST_NAME, USERID, SALARY)
VALUES (2, 'Darshana', 'Bala', 'bdarshana', 860);

SELECT * FROM MY_EMPLOYEES;

DECLARE @ID INT, @LAST_NAME VARCHAR(25), @FIRST_NAME VARCHAR(25), @SALARY DECIMAL(9,2);
SET @ID = 3;
SET @LAST_NAME = 'Mithra';
SET @FIRST_NAME = 'Janaki';
SET @SALARY = 920;

INSERT INTO MY_EMPLOYEES (ID, LAST_NAME, FIRST_NAME, USERID, SALARY)
VALUES (@ID, @LAST_NAME, @FIRST_NAME, LOWER(LEFT(@FIRST_NAME, 1) + LEFT(@LAST_NAME, 7)), @SALARY);

UPDATE MY_EMPLOYEES
SET LAST_NAME = 'Roy'
WHERE ID = 3;

UPDATE MY_EMPLOYEES
SET SALARY = 1000
WHERE SALARY < 900;

DELETE FROM MY_EMPLOYEES
WHERE LAST_NAME = 'Darshana' AND FIRST_NAME = 'Bala';

TRUNCATE TABLE MY_EMPLOYEES;


